-- Advanced Telegram deep-link delivery analytics.
CREATE TABLE IF NOT EXISTS video_delivery_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type TEXT NOT NULL CHECK (
    event_type IN (
      'attempt',
      'delivered',
      'force_sub_block',
      'limit_block',
      'not_found',
      'unavailable',
      'delivery_failed'
    )
  ),
  telegram_user_id BIGINT REFERENCES users(telegram_user_id) ON DELETE SET NULL,
  video_id BIGINT REFERENCES videos(id) ON DELETE SET NULL,
  code TEXT,
  source TEXT NOT NULL DEFAULT 'unknown' CHECK (
    source IN ('deep_link', 'search', 'callback', 'unknown')
  ),
  success BOOLEAN NOT NULL DEFAULT FALSE,
  error_message TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_video_delivery_events_created
  ON video_delivery_events(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_video_delivery_events_video
  ON video_delivery_events(video_id, event_type, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_video_delivery_events_user
  ON video_delivery_events(telegram_user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_video_delivery_events_code
  ON video_delivery_events(code, event_type, created_at DESC);
