-- Harden Telegram Stars payment processing.
-- The bot validates invoices before checkout; this function independently validates
-- the signed invoice payload shape and keeps the database as the final authority.
CREATE OR REPLACE FUNCTION complete_star_premium_payment(
  p_user_id BIGINT,
  p_payload TEXT,
  p_duration_days INTEGER,
  p_amount_stars INTEGER,
  p_currency TEXT,
  p_telegram_charge_id TEXT,
  p_provider_charge_id TEXT
)
RETURNS TABLE(success BOOLEAN, message TEXT, plan_expires_at TIMESTAMPTZ)
LANGUAGE plpgsql AS $$
DECLARE
  u users%ROWTYPE;
  ne TIMESTAMPTZ;
  payload_days INTEGER;
  payload_stars INTEGER;
  payload_user BIGINT;
BEGIN
  IF p_currency <> 'XTR'
     OR p_duration_days <= 0
     OR p_amount_stars <= 0
     OR p_telegram_charge_id IS NULL
     OR btrim(p_telegram_charge_id) = ''
     OR p_payload IS NULL
  THEN
    RETURN QUERY SELECT FALSE,'Invalid payment data.'::TEXT,NULL::TIMESTAMPTZ;
    RETURN;
  END IF;

  -- Payload format is generated by the bot:
  -- premium:<days>:<stars>:<telegram_user_id>
  IF p_payload !~ '^premium:[0-9]+:[0-9]+:[0-9]+$' THEN
    RETURN QUERY SELECT FALSE,'Invalid Premium invoice payload.'::TEXT,NULL::TIMESTAMPTZ;
    RETURN;
  END IF;

  payload_days := split_part(p_payload, ':', 2)::INTEGER;
  payload_stars := split_part(p_payload, ':', 3)::INTEGER;
  payload_user := split_part(p_payload, ':', 4)::BIGINT;

  IF payload_user <> p_user_id
     OR payload_days <> p_duration_days
     OR payload_stars <> p_amount_stars
     OR payload_days <= 0
     OR payload_stars <= 0
  THEN
    RETURN QUERY SELECT FALSE,'Payment does not match the Premium invoice.'::TEXT,NULL::TIMESTAMPTZ;
    RETURN;
  END IF;

  -- A Telegram charge ID is globally unique; the unique index is also the
  -- final concurrency guard against double activation.
  IF EXISTS (
    SELECT 1 FROM premium_payments
    WHERE telegram_payment_charge_id = p_telegram_charge_id
  ) THEN
    SELECT plan_expires_at INTO ne
    FROM users
    WHERE telegram_user_id = p_user_id;

    RETURN QUERY SELECT TRUE,'Payment was already processed.'::TEXT,ne;
    RETURN;
  END IF;

  SELECT * INTO u
  FROM users
  WHERE telegram_user_id = p_user_id
  FOR UPDATE;

  IF NOT FOUND OR u.is_blocked THEN
    RETURN QUERY SELECT FALSE,'Account is not eligible.'::TEXT,NULL::TIMESTAMPTZ;
    RETURN;
  END IF;

  ne := GREATEST(
    CASE
      WHEN u.plan='premium' AND u.plan_expires_at > NOW()
      THEN u.plan_expires_at
      ELSE NOW()
    END,
    NOW()
  ) + make_interval(days => p_duration_days);

  UPDATE users
  SET plan='premium',
      plan_expires_at=ne,
      updated_at=NOW()
  WHERE telegram_user_id=p_user_id;

  INSERT INTO premium_payments(
    telegram_user_id,
    payload,
    plan,
    duration_days,
    amount_stars,
    currency,
    telegram_payment_charge_id,
    provider_payment_charge_id
  )
  VALUES(
    p_user_id,
    p_payload,
    'premium',
    p_duration_days,
    p_amount_stars,
    p_currency,
    p_telegram_charge_id,
    p_provider_charge_id
  );

  RETURN QUERY SELECT TRUE,'Premium activated successfully.'::TEXT,ne;

EXCEPTION
  WHEN unique_violation THEN
    -- Covers a concurrent duplicate webhook/update racing the existence check.
    SELECT plan_expires_at INTO ne
    FROM users
    WHERE telegram_user_id=p_user_id;

    RETURN QUERY SELECT TRUE,'Payment was already processed.'::TEXT,ne;
END $$;